
[[pages]]
path = "app.py"
name = "AskMeAnything-Home"
icon = ":robot_face:"


[[pages]]
name = "Q&A-Chat"
icon = "â“"
is_section = true

[[pages]]
path = "src/qa_with_doc.py"
name = "Document"
icon = "ğŸ“œ"


[[pages]]
path = "src/qa_from_directory.py"
name = "Directory"
icon = "ğŸ“‚"


[[pages]]
path = "src/qa_with_website.py"
name = "WebPage_URL"
icon = "ğŸŒ"

[[pages]]
path = "src/qa_with_github_issues.py"
name = "Github_Issue"
icon = ":Git:"



[[pages]]
name = "Summarization"
icon = "ğŸ“"
is_section = true

[[pages]]
path = "src/Doc_Summarization.py"
name = "Document"
icon = "ğŸ“œ"

[[pages]]
path = "src/Github_Issue_Summarization.py"
name = "Github_Issues"
icon = ":Git:"


[[pages]]
path = "src/Doc_Summarization_with_directory.py"
name = "Directory"
icon = "ğŸ“‚"

[[pages]]
path = "src/Text_Summarization.py"
name = "Text"
icon = "ğŸ“°"


