[[pages]]
path = "app.py"
name = "Home"
icon = "ğŸ "


[[pages]]
name = "Q&A-Chat"
icon = "â“"
is_section = true

[[pages]]
path = "pages/Q&A_with_doc.py"
name = "Document"
icon = "ğŸ“œ"



[[pages]]
path = "pages/Q&A_with_website_page.py"
name = "WebPage_URL"
icon = "ğŸŒ"


[[pages]]
name = "Summarization"
icon = "ğŸ“"
is_section = true

[[pages]]
path = "pages/Doc_Summarization.py"
name = "Document"
icon = "ğŸ“œ"

[[pages]]
path = "pages/Doc_Summarization_with_directory.py"
name = "Directory"
icon = "ğŸ“‚"

[[pages]]
path = "pages/Text_Summarization.py"
name = "Text"
icon = "ğŸ“°"


